name: E2E in custom container

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    # https://hub.docker.com/r/cypress/browsers/tags?page=1&ordering=last_updated
    container: cypress/browsers:node12.6.0-chrome77
    steps:
      - uses: actions/checkout@v2
      - name: test
        run: |
          yarn
          yarn run test:ci
        
